### PR TITLE
Implement pdf compare and fix download manager

### LINKED ISSUE #301: Fix download directory creation and fetching during chrome setup
- Current behavior is unclear as written. Download directory for chrome is fetched and/or created multiple places and does not work properly if custom value is used.
- As a result, download monitoring is broken.

### PR DESCRIPTION
**Pull request by sampacos**
- implement #300
- fix #301 download directory issues with chrome.
-  add unit tests. add pdfs to use in comparison tests.

### CODE REVIEW

File: src/test/java/com/dougnoel/sentinel/filemanagers/DownloadManagerTests.java [hunk 1]
```diff
@@ -18,5 +18,25 @@ public void testVerifyTextNotInDownloadedPDFPageTwo() {
...
+		File file = new File("src/test/resources/pdfs/TestPDF.pdf");
+		File file2 = new File("src/test/resources/pdfs/TestPDF_different.pdf");
+		assertFalse("Expecting PDF to match a copy of itself.", DownloadManager.verifyDownloadedPDFViaVisualRendering(file, file2));
+	}
+	
+	@Test
+	public void testVerifyPDFComparisonViaRendering_OutputFileError() {
+		File file = new File("src/test/resources/pdfs/TestPDF.pdf");
+		File file2 = new File("src/test/resources/pdfs/TestPDF_different.pdf");
+		assertFalse("Expecting PDF to match a copy of itself.", DownloadManager.verifyDownloadedPDFViaVisualRendering(file, file2, 0.0, "/bin/bash"));
```
Comment (dougnoel) [inline src/test/java/com/dougnoel/sentinel/filemanagers/DownloadManagerTests.java:40]: Pretty sure this message is not correct but I don't understand why this is different.

**Review by dougnoel — APPROVED** [review]
